=  CHANGELOG

==  ciigo v0.5.0 (2021-02-21)

=== New features

* all: implement Watch functionality

  The Watch function, watch any changes on asciidoc files on directory
  "dir" recursively and changes on the HTML template file.
  If there is new or modified asciidoc files it will convert them into HTML
  files using HTML template automatically.

  If the HTML template file modified, it will re-convert all asciidoc files.
  If the HTML template file deleted, it will replace them with internal,
  default HTML template.

=== Breaking changes

* all: return error instead of call log.Fatal on non main packages

  The library, non-main packages, should never call Fatal or panic,
  its up to the main package or the caller on how to handle it.

  While at it, fix the returned error to use log prefix and the error
  value, remove the "ciigo: " prefix.

=== Chores

* all: rewrite to use the watcher

  Now that we have the watcher which task are to watch the asciidoc
  files and template files, we can use it in server to minimize duplicate
  code.

  This changes refactoring the htmlGenerator to initialize the HTML
  template from internal or memfs, so the caller did not need to check by
  itself.


==  ciigo v0.4.1 (2021-01-21)

Update to latest share module.

Fix the HTTP server not auto-reload the new changes if DEBUG value is
non-zero.


==  ciigo v0.4.0 (2021-01-21)

Refactoring due to change on memfs package.

This changes affect the exported functions Generate() and Serve().

Previously, the Generate() function accept three options: dir, out,
and htmlTemplate; this release changes the parameter into single struct
Options with two additional options: GenPackageName and GenVarName.
The GenPackageName allow to set the package name in Go generate source
code, default to "main" if not set.
The GenVarName set the instance of memfs.MemFS where the embedded
files will be stored.

On the Serve() function, we add parameter to pass the instance of
memfs.MemFS (the one that passed on GenVarName).


==  ciigo v0.3.0 (2020-12-06)

This release replace the asciidoc parsing from libasciidoc-go to
https://sr.ht/~shulhan/asciidoctor-go[asciidoctor-go], which provide more
control and stable APIs.

We also remove support form markdown markup language and focus only to support
asciidoctor format from now on.

The Go module path and repository is also moved from github to
git.sr.ht/~shulhan/ciigo.


==  ciigo v0.2.0 (2020-07-05)

* all: simplify serving content using function Serve
  Previously to serve the generated content we call two fucntions:
  NewServer() and Server.Start().
  This changes unexported the internal server, and expose only the Serve()
  function with the same parameter as NewServer().

* all: embed the HTML template and the stylesheet
  The parameter for template either in Convert or Generate functions or
  in CLI now become pure optional, not default to "templates/html.tmpl"
  anymore.
  This will minimize steps for user to setup or run the library or program.

==  ciigo v0.1.1 (2020-03-24)

The first release support asciidoc and markdown markup language.

The v0.1.0 release has been deleted because it contains error in the
dependencies and the Go module cache make it even harder to invalidate it.
