=  Welcome to ciigo
:stylesheet: /assets/style.css

`ciigo` is a program to write static web server with embedded files using
generated markup format.

Currently, ciigo support
https://asciidoctor.org/docs/what-is-asciidoc/[asciidoc]
and
https://commonmark.org/[markdown]
as markup format.


==  Document Structure

This software use the following directory structure and file name
conventions,

*  `cmd/<name>`: this is the program that serve the generated content.

*  `content`: the root directory of static and generated content to be
   embedded and served.
   This is where markup files must be saved.
   Any files inside this directory, except in "content/assets", will be
   ignored.

*  `content/assets`: contains static files (images, js, css) that can be
   accessed by any pages using absolute path under `/assets/`.

*  `templates`: contains dynamic templates.  Currently. there is only single
   template: `html.tmpl`, that wrap the generated HTML.

*  All markup files inside content must have an ".adoc" extension.


==  Getting Started

This section describe step by step instructions on how to build and create
pages to be viewed for local development using `ciigo`.

.  Clone the `ciigo` repository.
For example, lets say we have cloned the `ciigo` repository into
`$HOME/go/src/github.com/shuLhan/ciigo`.

.  Create new Go repository for building a website.
For example, in directory `$HOME/go/src/remote.tld/user/mysite`.
Replace "remote.tld/user/mysite" with your private or public repository.
+
----
$ mkdir -p $HOME/go/src/remote.tld/user/mysite
$ cd $HOME/go/src/remote.tld/user/mysite
----

.  If you use Go module, create the Go module; if you use GOPATH ignore this
   step.
+
----
$ go mod init remote.tld/user/mysite
----

.  Create directories for storing our content and a package binary.
ciigo use strict directory structure as we have mention above.
+
----
$ mkdir -p cmd/mysite
$ mkdir -p content/assets
$ mkdir -p templates
----

.  Copy the example of stylesheet and HTML template from `ciigo` repository,
+
----
$ cp $HOME/go/src/github.com/shuLhan/ciigo/content/assets/style.css ./content/assets/
$ cp $HOME/go/src/github.com/shuLhan/ciigo/templates/html.tmpl ./templates/
----

.  Create a Go source code in the root repository to generate all markup files
   inside "content" directory into HTML.
   Lets named it `generate.go` with the following content,
+
----
//go:generate go run generate.go

package main

import (
        "github.com/shuLhan/ciigo"
)

func main() {
        ciigo.Generate("./content", "cmd/mysite/static.go")
}
----

.  Create the main Go code inside `cmd/mysite`,
+
----
package main

import (
        "github.com/shuLhan/ciigo"
)

func main() {
        srv := ciigo.NewServer("./content", ":8080")

        srv.Start()
}
----

.  Create a new markup file `index.adoc` inside "content" directory.
   Each directory, or sub directory, should have `index.adoc` to be able to
   accessed by browser,
+
----
=  Test
:stylesheet: /assets/style.css

Hello, world!
----

.  Run `go generate` to convert all files with extension `.adoc` (or `.md`)
   into HTML and embed it into `./cmd/mysite/static.go`
+
	$ go generate

.  Now run the `./cmd/mysite` with `DEBUG` environment variable is set,
+
----
$ export DEBUG=1
$ go run ./cmd/mysite
----
+
Any non zero value on `DEBUG` environment signal the running program to watch
changes in ".adoc" files inside "content" directory and serve the generated
HTML directly.

.  Open the web browser at `localhost:8080` to view the generated HTML.
You should see "Hello, world!" as the main page.

Thats it!

Create or update any ".adoc" files in "content" directory, the program will
automatically generated the HTML file, but you still need to refresh the web
browser to load the new generated file.


==  Deployment

First, we need to convert all markup files inside "content" into HTML and
dump the content of all static files inside "content",

----
$ go generate
----

The above command will generate Go source code in `cmd/mystite/static.go`.

Second, build the web server that serve static contents in `static.go`,

----
$ go build cmd/ciigo
----

Third, test the web server by running the program and opening `localhost:8080`
on web browser,

----
$ ./ciigo
----

Finally, deploy the program to your server.

*NOTE:* By default, server will listen on address `0.0.0.0` at port `8080`.
If you need to use another port, you can change it at `cmd/mysite/main.go`.


==  Limitations and Known Bugs

`ciigo` will not handle automatic certificate (e.g. using LetsEncrypt), its
up to administrator how the certificate are gathered or generated.

Using symlink on ".adoc" file inside `content` directory is not supported yet.


==  Resources

The source code for this software can be viewed at
https://github.com/shuLhan/ciigo
under custom link:/LICENSE[BSD license].


==  Credits

This software is developed with helps from third party libraries.
The following section list only direct third party library.

*  https://github.com/bytesparadise/libasciidoc[libasciidoc].
   https://raw.githubusercontent.com/bytesparadise/libasciidoc/master/LICENSE[License].

*  https://github.com/yuin/goldmark[goldmark].
   https://raw.githubusercontent.com/yuin/goldmark/master/LICENSE[License].
